// Practice controller — request → domain call → DB read/write → response.
//
// The controller is transport-only: it parses with Zod, calls
// `@pt/domain` for ordering, calls the repository for I/O, and
// validates the response shape with `@pt/contracts`. The Phase A
// `practice/router.ts` inlined this logic; Phase B splits it into
// `repository.ts` (DB) and `controller.ts` (HTTP + validation).
//
// Per CONTEXT.md "Error Envelope", every 4xx/5xx response carries
// `{ error: { code, message, correlationId } }`. The
// `correlationId` is generated by the auth middleware chain
// (`res.locals.correlationId`); we read it where present, generate
// one when the route fires before the middleware.

import { randomUUID } from 'node:crypto';
import type { Request, Response } from 'express';
import {
  practiceQueueResponseSchema,
  practiceQueueQuerySchema,
  ratingWriteSchema,
  reviewQueueResponseSchema,
  smartReviewQuerySchema,
  errorEnvelopeSchema,
  type PracticeQueueResponse,
  type ReviewQueueResponse,
  type ErrorCode,
} from '@pt/contracts';
import {
  buildPracticeQueue,
  buildReviewQueue,
  type PracticeItem,
  type ReviewRating,
} from '@pt/domain';
import {
  loadActiveCvId,
  loadRatingsForUserMode,
  loadSentencesForUnit,
  upsertRating,
} from './repository.js';

// ---------- Headers -----------------------------------------------------

const NO_STORE = 'no-store' as const;
const PRIVATE_MAX_AGE_60 = 'private, max-age=60' as const;

// ---------- handlers ----------------------------------------------------

export async function rate(req: Request, res: Response): Promise<void> {
  const userId = req.userIdFromAuth();
  if (!userId) {
    sendError(res, 401, 'unauthorized', 'Authentication required');
    return;
  }

  const parsed = ratingWriteSchema.safeParse(req.body);
  if (!parsed.success) {
    sendError(res, 400, 'validation_failed', parsed.error.issues.map((i) => i.message).join('; '));
    return;
  }

  const row = await upsertRating({ ...parsed.data, userId });
  res.setHeader('Cache-Control', NO_STORE);
  res.status(200).json({
    sentenceId: row.sentenceId,
    mode: row.mode,
    rating: row.rating,
    lastPractisedAt: row.lastPractisedAt.toISOString(),
  });
}

export async function queue(req: Request, res: Response): Promise<void> {
  const userId = req.userIdFromAuth();
  if (!userId) {
    sendError(res, 401, 'unauthorized', 'Authentication required');
    return;
  }

  const parsed = practiceQueueQuerySchema.safeParse(req.query);
  if (!parsed.success) {
    sendError(res, 400, 'validation_failed', parsed.error.issues.map((i) => i.message).join('; '));
    return;
  }

  const cvId = await loadActiveCvId();
  if (!cvId) {
    sendError(res, 500, 'internal', 'No active curriculum version found');
    return;
  }

  const sentences = await loadSentencesForUnit(parsed.data.unitId, cvId);
  // `buildPracticeQueue` returns `ReadonlyArray<PracticeItem>`;
  // widen to a mutable array via `Array.from` so the response
  // object satisfies the `practiceQueueResponseSchema` shape
  // (which infers `items` as a mutable array).
  const items = Array.from(
    buildPracticeQueue(sentences, {
      mode: parsed.data.mode,
      sortOrder: 'curriculum',
    }),
  );

  const response: PracticeQueueResponse = { items };
  const validated = practiceQueueResponseSchema.safeParse(response);
  if (!validated.success) {
    sendError(res, 500, 'internal', 'queue response shape invalid');
    return;
  }

  // Per amendment A6: /api/practice/queue carries Cache-Control:
  // private, max-age=60 + an ETag derived from the active CV id.
  // The middleware prefix rules emit `no-store` for /api/practice/*
  // GETs by default; the controller overrides here for the queue.
  res.setHeader('Cache-Control', PRIVATE_MAX_AGE_60);
  res.setHeader('ETag', `"${cvId}"`);
  res.status(200).json(validated.data);
}

export async function review(req: Request, res: Response): Promise<void> {
  const userId = req.userIdFromAuth();
  if (!userId) {
    sendError(res, 401, 'unauthorized', 'Authentication required');
    return;
  }

  const parsed = smartReviewQuerySchema.safeParse(req.query);
  if (!parsed.success) {
    sendError(res, 400, 'validation_failed', parsed.error.issues.map((i) => i.message).join('; '));
    return;
  }

  const cvId = await loadActiveCvId();
  if (!cvId) {
    sendError(res, 500, 'internal', 'No active curriculum version found');
    return;
  }

  // Phase B practice surfaces a single unit (a1_introductions)
  // today. Phase C introduces per-unit review; until then the unit
  // is hard-coded and the smart-review queue is the a1
  // introductions set, filtered by `mode`.
  const sentences = await loadSentencesForUnit('unit_a1_introductions', cvId);
  const ratingRows = await loadRatingsForUserMode(userId, parsed.data.mode);

  const ratings = new Map<string, ReviewRating>();
  for (const r of ratingRows) {
    ratings.set(r.sentenceId, {
      mode: r.mode,
      rating: r.rating,
      lastPractisedAt: r.lastPractisedAt,
    });
  }

  // `buildReviewQueue` returns `ReadonlyArray<PracticeItem>`;
  // widen to a mutable array via `Array.from` (same pattern
  // as the queue handler above). The `ReviewQueueResponse`
  // schema extends `practiceItemSchema` with a REQUIRED
  // `rating` field, so `items[i]` here is `PracticeItem & {
  // rating: number }` once the schema's `.extend()` applies.
  const items = Array.from(
    buildReviewQueue(ratings, sentences, parsed.data.mode, parsed.data.limit),
  ) as unknown as ReviewQueueResponse['items'];

  const response: ReviewQueueResponse = { items };
  const validated = reviewQueueResponseSchema.safeParse(response);
  if (!validated.success) {
    sendError(res, 500, 'internal', 'review response shape invalid');
    return;
  }

  res.setHeader('Cache-Control', PRIVATE_MAX_AGE_60);
  res.setHeader('ETag', `"${cvId}"`);
  res.status(200).json(validated.data);
}

// ---------- error envelope --------------------------------------------

function sendError(
  res: Response,
  httpStatus: number,
  code: ErrorCode,
  message: string,
): void {
  const envelope = errorEnvelopeSchema.parse({
    error: { code, message, correlationId: randomUUID() },
  });
  res.status(httpStatus).json(envelope);
}
