import type { Level } from "@/lib/curriculum/types";

const A0_WORDS: readonly string[] = [
  "olá",
  "oi",
  "bom",
  "boa",
  "dia",
  "tarde",
  "noite",
  "adeus",
  "tchau",
  "sim",
  "não",
  "por favor",
  "obrigado",
  "obrigada",
  "de nada",
  "eu",
  "tu",
  "ele",
  "ela",
  "nós",
  "eles",
  "elas",
  "e",
  "ou",
  "mas",
  "um",
  "uma",
  "o",
  "a",
  "os",
  "as",
  "este",
  "esta",
  "isso",
  "isto",
  "aquilo",
  "que",
  "qual",
  "como",
  "onde",
  "quando",
  "ser",
  "estar",
  "ter",
  "haver",
  "ir",
  "fazer",
  "dizer",
  "saber",
  "ver",
  "dar",
  "chamar",
  "muito",
  "pouco",
  "mais",
  "menos",
  "tudo",
  "nada",
  "também",
  "já",
  "ainda",
  "hoje",
  "ontem",
  "amanhã",
  "praça",
  "banco",
  "loja",
  "correio",
  "praia",
];

const A1_WORDS: readonly string[] = [
  "café",
  "água",
  "leite",
  "pão",
  "ovo",
  "carne",
  "peixe",
  "sal",
  "açúcar",
  "conta",
  "mesa",
  "cadeira",
  "amigo",
  "amiga",
  "família",
  "mãe",
  "pai",
  "irmão",
  "irmã",
  "filho",
  "filha",
  "casa",
  "escola",
  "trabalho",
  "rua",
  "cidade",
  "país",
  "Portugal",
  "Lisboa",
  "Porto",
  "Coimbra",
  "Faro",
  "Sintra",
  "Cascais",
  "querer",
  "poder",
  "queres",
  "tens",
  "estou",
  "está",
  "sou",
  "somos",
  "vou",
  "vamos",
  "dou",
  "dás",
  "damos",
  "gosto",
  "gostas",
  "preciso",
  "precisas",
  "querido",
  "querida",
  "bom dia",
  "boa tarde",
  "boa noite",
  "como estás",
  "como vai",
  "até logo",
  "até amanhã",
  "desculpa",
  "desculpe",
  "com licença",
  "está bem",
  "muito bem",
  "tens de",
  "um bocado",
  "talvez",
  "aqui",
  "ali",
  "lá",
  "neste",
  "nesta",
  "daquele",
  "daquela",
  "ano",
  "anos",
  "mês",
  "meses",
  "semana",
  "dia",
  "hora",
  "horas",
  "minuto",
  "minutos",
  "manhã",
  "tarde",
  "noite",
  "receita",
  "médico",
  "doente",
  "febre",
  "tosse",
  "dor",
  "cabeça",
  "barriga",
  "remédio",
  "comprimido",
  "táxi",
  "autocarro",
  "comboio",
  "metro",
  "bilhete",
  "passaporte",
  "mala",
  "voo",
  "aeroporto",
  "hotel",
  "quarto",
  "reserva",
  "pequeno-almoço",
  "almoço",
  "jantar",
  "ementa",
  "conta",
  "gorjeta",
];

const A2_WORDS: readonly string[] = [
  "ontem",
  "anteontem",
  "de manhã",
  "de tarde",
  "de noite",
  "fim de semana",
  "sempre",
  "nunca",
  "às vezes",
  "raramente",
  "fui",
  "foste",
  "foi",
  "fomos",
  "foram",
  "tinha",
  "tinhas",
  "tínhamos",
  "tinham",
  "fiz",
  "fizeste",
  "fez",
  "fizemos",
  "fizeram",
  "vi",
  "viste",
  "viu",
  "vimos",
  "viram",
  "disse",
  "disseste",
  "disseram",
  "saí",
  "saíste",
  "saiu",
  "saímos",
  "saíram",
  "viagem",
  "férias",
  "campo",
  "montanha",
  "jornal",
  "televisão",
  "filme",
  "música",
  "livro",
  "comprei",
  "compraste",
  "comprou",
  "vendi",
  "vendeste",
  "vendeu",
  "aluguei",
  "alugou",
  "recebi",
  "recebeu",
  "perdi",
  "perdeu",
  "encontrei",
  "encontrou",
  "procurei",
  "procurou",
  "lembrei",
  "lembrou",
  "esqueci",
  "esqueceu",
  "conheço",
  "conheces",
  "conhece",
  "sei",
  "sabes",
  "sabe",
  "gostava",
  "queria",
  "podias",
  "devias",
  "mau",
  "má",
  "pior",
  "melhor",
  "bonito",
  "bonita",
  "feio",
  "feia",
  "grande",
  "pequeno",
  "pequena",
  "novo",
  "nova",
  "velho",
  "velha",
  "rápido",
  "rápida",
  "lento",
  "lenta",
  "perto",
  "longe",
  "antes",
  "depois",
  "cedo",
  "atrasado",
  "chovia",
  "choveu",
  "fazia sol",
  "estava nublado",
  "transferi",
  "levantou",
  "levantámos",
  "saquei",
  "depositei",
  "carreguei",
  "paguei",
  "recebi",
  "abri",
  "fechei",
  "alugámos",
  "arrendámos",
  "matriculei-me",
  "inscrevi-me",
  "candidatei-me",
];

const B1_WORDS: readonly string[] = [
  "acho",
  "achamos",
  "acham",
  "porque",
  "embora",
  "contudo",
  "porém",
  "todavia",
  "no entanto",
  "portanto",
  "logo",
  "assim",
  "deste modo",
  "além disso",
  "por isso",
  "com efeito",
  "na verdade",
  "de facto",
  "aliás",
  "pois",
  "opinião",
  "ideia",
  "pensamento",
  "razão",
  "motivo",
  "causa",
  "consequência",
  "problema",
  "solução",
  "decisão",
  "escolha",
  "mudança",
  "diferença",
  "semelhança",
  "acordo",
  "discurso",
  "discussão",
  "debate",
  "política",
  "sociedade",
  "cultura",
  "tradição",
  "história",
  "economia",
  "tecnologia",
  "ambiente",
  "educação",
  "saúde",
  "segurança",
  "liberdade",
  "igualdade",
  "responsabilidade",
  "desenvolvimento",
  "experiência",
  "conhecimento",
  "informação",
  "comunicação",
  "relação",
  "influência",
  "objectivo",
  "objectivos",
  "propósito",
  "intenção",
  "pretendo",
  "pretendes",
  "pretende",
  "considero",
  "consideras",
  "considera",
  "parece-me",
  "parece-te",
  "parece-lhe",
  "na minha opinião",
  "do meu ponto de vista",
  "tem razão",
  "não tem razão",
  "concordo",
  "concordas",
  "concorda",
  "discordo",
  "discordas",
  "discorda",
  "interessante",
  "importante",
  "necessário",
  "possível",
  "impossível",
  "provável",
  "improvável",
  "provavelmente",
  "certamente",
  "possivelmente",
  "felizmente",
  "infelizmente",
  "espero",
  "esperas",
  "espera",
  "desejo",
  "desejas",
  "deseja",
  "preocupo-me",
  "preocupas-te",
  "preocupa-se",
  "interesso-me",
  "interessas-te",
  "interessa-se",
  "estágio",
  "entrevista",
  "currículo",
  "salário",
  "ordenado",
  "benefícios",
  "horário",
  "férias",
  "baixa",
  "despedimento",
  "reforma",
  "segurança social",
  "impostos",
  "recibo",
  "factura",
  "contrato",
  "multibanco",
  "balcão",
  "caixa",
  "agência",
  "cartão",
  "crédito",
  "débito",
  "transferência",
];

const VOCABULARY_BY_LEVEL: Record<Level, ReadonlySet<string>> = {
  A0: new Set(A0_WORDS),
  A1: new Set([...A0_WORDS, ...A1_WORDS]),
  A2: new Set([...A0_WORDS, ...A1_WORDS, ...A2_WORDS]),
  B1: new Set([...A0_WORDS, ...A1_WORDS, ...A2_WORDS, ...B1_WORDS]),
};

export function vocabularyFor(level: Level): ReadonlySet<string> {
  return VOCABULARY_BY_LEVEL[level];
}

export const SUB_LEVELS = ["A2.1", "A2.2", "B1.1", "B1.2"] as const;
export type SubLevel = (typeof SUB_LEVELS)[number];

const A2_1_WORDS: readonly string[] = [
  "estabeleci",
  "estabeleceu",
  "comprometi-me",
  "comprometeu-se",
  "aconselhei",
  "aconselhámos",
  "recusei",
  "recusou",
  "aceitei",
  "aceitou",
  "desisti",
  "desistiu",
  "convenci",
  "convenceu",
  "convenceram",
  "insisti",
  "insistiu",
  "sugeri",
  "sugeriu",
  "sugeriram",
  "recomendei",
  "recomendou",
];

const A2_2_WORDS: readonly string[] = [
  "emprego",
  "desemprego",
  "estagiário",
  "formação",
  "qualificação",
  "experiência profissional",
  "candidatura",
  "anúncio",
  "entrevistador",
  "recrutador",
  "salário mínimo",
  "subsídio",
  "férias remuneradas",
  "horário flexível",
  "teletrabalho",
  "presencial",
  "reuniões",
  "relatório",
  "apresentação",
  "prazo",
  "objectivo profissional",
];

const B1_1_WORDS: readonly string[] = [
  "narrativa",
  "contexto",
  "perspectiva",
  "premissa",
  "tese",
  "argumento",
  "contra-argumento",
  "refutação",
  "evidência",
  "fonte",
  "fiável",
  "credível",
  "parcial",
  "imparcial",
  "subjetivo",
  "objectivo",
  "ambíguo",
  "preciso",
  "rigoroso",
  "aprofundar",
  "aprofundei",
  "aprofundámos",
  "elaborei",
  "elaborámos",
  "desenvolvi",
  "desenvolveu",
];

const B1_2_WORDS: readonly string[] = [
  "poliglota",
  "multilingue",
  "língua materna",
  "língua estrangeira",
  "aquisição",
  "imergir",
  "imersão",
  "fluência",
  "proficiência",
  "competência",
  "desempenho",
  "avaliação",
  "auto-avaliação",
  "feedback",
  "progresso",
  "regressão",
  "plateau",
  "avanço",
  "recuo",
  "consolidação",
  "generalização",
  "transferência",
  "metalinguagem",
  "metacognição",
];

export function isSubLevel(value: string): value is SubLevel {
  return (SUB_LEVELS as readonly string[]).includes(value);
}

export function subLevelParent(sub: SubLevel): Level {
  if (sub === "A2.1" || sub === "A2.2") return "A2";
  return "B1";
}

export function vocabularyForSubLevel(sub: SubLevel): ReadonlySet<string> {
  const parent = subLevelParent(sub);
  const parentWords = VOCABULARY_BY_LEVEL[parent];
  const additions =
    sub === "A2.1"
      ? A2_1_WORDS
      : sub === "A2.2"
        ? A2_2_WORDS
        : sub === "B1.1"
          ? B1_1_WORDS
          : B1_2_WORDS;
  return new Set([...parentWords, ...additions]);
}

export function assertMonotonicVocabulary(): void {
  const sets: Record<Level, ReadonlySet<string>> = VOCABULARY_BY_LEVEL;
  const order: Level[] = ["A0", "A1", "A2", "B1"];
  for (let i = 1; i < order.length; i += 1) {
    const prev = sets[order[i - 1]!]!;
    const curr = sets[order[i]!]!;
    for (const word of prev) {
      if (!curr.has(word)) {
        throw new Error(
          `Vocabulary monotonicity violated: '${word}' present at ${order[i - 1]} but missing at ${order[i]}`,
        );
      }
    }
  }

  for (const sub of SUB_LEVELS) {
    const parentWords = VOCABULARY_BY_LEVEL[subLevelParent(sub)];
    const subWords = vocabularyForSubLevel(sub);
    for (const word of parentWords) {
      if (!subWords.has(word)) {
        throw new Error(
          `Sub-level monotonicity violated: '${word}' present at parent of ${sub} but missing in sub-level vocab`,
        );
      }
    }
  }
}

export function vocabularyStats(): {
  byLevel: Record<Level, number>;
  bySubLevel: Record<SubLevel, number>;
  totalUnique: number;
} {
  const byLevel: Record<Level, number> = {
    A0: VOCABULARY_BY_LEVEL.A0.size,
    A1: VOCABULARY_BY_LEVEL.A1.size,
    A2: VOCABULARY_BY_LEVEL.A2.size,
    B1: VOCABULARY_BY_LEVEL.B1.size,
  };
  const bySubLevel: Record<SubLevel, number> = {
    "A2.1": vocabularyForSubLevel("A2.1").size,
    "A2.2": vocabularyForSubLevel("A2.2").size,
    "B1.1": vocabularyForSubLevel("B1.1").size,
    "B1.2": vocabularyForSubLevel("B1.2").size,
  };
  const all = new Set<string>();
  for (const set of Object.values(VOCABULARY_BY_LEVEL)) {
    for (const word of set) all.add(word);
  }
  for (const set of Object.values(bySubLevel)) {
    for (const word of vocabularyForSubLevel("A2.1")) all.add(word);
  }
  return { byLevel, bySubLevel, totalUnique: all.size };
}